### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/fable-doc#11]
Hi, are there any thoughts on API documentation?
When using Fable.React I often need to look in the source code to see what goes wrong in my own code. It would be nice if there was also some form of technical documentation.

**Comment by MangelMaxime** [comment]
If we need to document `Fable.React` it's better to do it in the `Fable.React` repo.

IHMO, here we are documenting Fable itself not the libraries. I can set up `Nacara` in other repo where it makes sense.

And also, the benefit of documenting `Fable.React` in its own repo is because `Nacara` should in the future support versioning of the documentation. So people could see the documentation of `5.x` and `6.x` etc.

**Comment by alfonsogarciacaro** [comment]
Yes, Fable.React (and other libraries) should include more documentation through doc comments. But I guess @nojaf talks about a way to put this documentation in a website like [other F# projects do](https://fake.build/apidocs/v5/index.html). There was a similar contribution to get Fable.Core API in the website, but it broke and I didn't know how to fix it so I just deleted it 😸 TBH, I think API documentation is only useful when it's very comprehensive, which is difficult in OSS projects. But yeah, it'd be a nice-to-have.

**Comment by whitetigle** [comment]
> I think API documentation is only useful when it's very comprehensive, which is difficult in OSS projects. But yeah, it'd be a nice-to-have.

For bindings that could be a good fit. Of cours it depends on the maturity of the project. But for `fable-node` for instance, it could be a good match since I ended up writing tests as well so we could add them to as samples in the API documentation.

**Comment by alfonsogarciacaro** [comment]
Closing as the documentation here is not intended to cover specific libraries (at least not extensively) but Fable overall.
