### ISSUE TITLE
How do you push a new version of the docs?

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fable-doc#16]

**Comment by whitetigle** [comment]
Push, like make a new version available? 

Umm, I guess by generating the doc and updating the `docs` folder (if I understand well what I see in the repo Settings)

![image](https://user-images.githubusercontent.com/883207/57637315-66703d80-75ab-11e9-8574-42f97b657806.png)

But I must admit I did not push a new version since @MangelMaxime put the new system live. I can't try right now but I'll check a little bit later

**Comment by Zaid-Ajaj** [comment]
If you have a build step and don't want to include files of the generated (static) website in the master branch (the docs folder) but instead in another branch like gh-pages, then see how puppeteer-sharp does this using appveyor, they include a [directory called appveyor](https://github.com/kblok/puppeteer-sharp/tree/master/appveyor) in master which AFAIK builds and pushes the generated assets into gh-pages. The credentials for the `git push` command are provided as environment variable via appveyor

> I haven't tried this before myself

**Comment by MangelMaxime** [comment]
Yes, with the current configuration it is being published from `docs` folder.

So when developing, locally using `npm run nacara` it's published immediately with your changes.

Nacara doesn't have a build only mode. It only has a watch mode. I am working on it and when ready we will be able to use a CI to build the docs and publish it on another branch for example.

**Comment by whitetigle** [comment]
Just pushed a new version with latest updates.
