### ISSUE TITLE
Review process

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable-doc#4]
Invoking @alfonsogarciacaro 🍷 🎸 💃

**Comment by alfonsogarciacaro** [comment]
Hi! I had a quick look through the docs. I want to send a PR with changes, especially for the compatibility and interop pages, but for now please find below some comments I wrote down while reading:

- First of all, thanks a lot for writing the docs and to @MangelMaxime for formatting them. This is going to be tremendously helpful for Fable users. I like the style of the docs, the only thing I'm missing is a favicon :)
- It'd be great if we could ask a native English speaker to review the foreword.
- Maybe I'm too pessimistic, but I've the feeling that some overoptimistic comments could be toned down ;) Like saying that Fable is extensively used in so many fields (users may expect more support, samples, tutorials and libraries for all these fields). But I'm not sure, maybe we need indeed to exaggerate a bit to promote Fable :)
- We could add links when mentioning tools like Babel or Webpack
- I would give precedence to npm over yarn (or even discard yarn at all). It's easier to install as it comes with node, already has a lock file and automatically audits your packages for security issues.
- **Setup**: In the editors section, I'd remove “free” (some have paid options), add Visual Studio (and VS for Mac although I haven’t used it for a while), and move Rider up in the list.
- **Start a new project**: I'd say "samples" instead of "templates" (which can be confused with dotnet templates or another templating system)
- **Add a new file**: mention that some editors do this for you (VS, Rider) and that file order in F# is important.
- **Use a Fable library**: Maybe we can remove the explanation about .dll for general users (actually the .dll is used by editors, but Fable needs the source files in most cases so the compilation times is not faster). Also mention you can use the dotnet SDK command: `dotnet add package Fable.Elmish.React [-v 3.0.1]` and that some editors (VS, Rider) manage packages for you.
- **Use a Fable library: Important considerations**: Maybe just reduce this to a note saying: “Please note the library must be specifically Fable-compatible in order to work.” Then we can add a link to another section for library authors to list the things necessary to write a library compatible with Fable, as in here: https://fable.io/faq/#library-authors
- **Build & Run**: I would focus on Webpack for web projects instead of talking about npm start
- **Call JS from Fable**: I need to go through this document more throughly to make sure everything is up-to-date :)
- **Call Fable from JS**: We should add a note about name mangling in Fable, I’ll do that.
- **Numbers**: `decimal` is currently not compiled to JS number, this is outdated in the docs, sorry! Add also a link to next document for number caveats when coming from .NET

**Comment by MangelMaxime** [comment]
> the only thing I'm missing is a favicon :)

Ok noted, I will add support for it.

> I would give precedence to npm over yarn (or even discard yarn at all). It's easier to install as it comes with node, already has a lock file and automatically audits your packages for security issues.

Don't forget that it's slow as hell too :p

> Start a new project: I'd say "samples" instead of "templates" (which can be confused with dotnet templates or another templating system)

I agree they are more samples than templates because.

> Use a Fable library: Maybe we can remove the explanation about .dll for general users (actually the .dll is used by editors, but Fable needs the source files in most cases so the compilation times is not faster). Also mention you can use the dotnet SDK command: dotnet add package Fable.Elmish.React [-v 3.0.1] and that some editors (VS, Rider) manage packages for you.

I think the first paragraph of this page should be removed indeed. Because it's how standard F# packages work. If we want to make a note about `Nuget` and Fable libraries we could say that in general Fable libraries can be identified because they start  with `Fable.*`

> Use a Fable library: Important considerations: Maybe just reduce this to a note saying: “Please note the library must be specifically Fable-compatible in order to work.” Then we can add a link to another section for library authors to list the things necessary to write a library compatible with Fable, as in here: https://fable.io/faq/#library-authors

TBH, I don't like the F.A.Q page style it's hard to read and find the information on it. Also, I do think we could benefit from a dedicated page called "Creating a Fable library" and we could walk step by step on how it can be done.

1. Creating the F# project
2. balaba
3. The needs to include the F# sources under a `fable` package and all others resources too.

> Build & Run: I would focus on Webpack for web projects instead of talking about npm start

It should indeed be more generalist. I guess some people could come to this section without having to start with a sample.

**Comment by whitetigle** [comment]
> First of all, thanks a lot for writing the docs and to @MangelMaxime for formatting them. This is going to be tremendously helpful for Fable users. I like the style of the docs, the only thing I'm missing is a favicon :)

Hey, Thanks for taking time to read the doc. I'm very happy you like it! And we'll add a nice disco purple favicon 😉 

> It'd be great if we could ask a native English speaker to review the foreword.
Yes and maybe read and correct mistakes and maybe formulation, because I fear there's quite a few part where my English looks like Latin English ;)

>Maybe I'm too pessimistic, but I've the feeling that some overoptimistic comments could be toned down ;) Like saying that Fable is extensively used in so many fields (users may expect more support, samples, tutorials and libraries for all these fields). But I'm not sure, maybe we need indeed to exaggerate a bit to promote Fable :)

Agreed!

> We could add links when mentioning tools like Babel or Webpack

Agreed!

> I would give precedence to npm over yarn (or even discard yarn at all). It's easier to install as it comes with node, already has a lock file and automatically audits your packages for security issues.

Yes, we've been discussing this with @MangelMaxime. Maybe we should focus on `npm` but clearly mention somewhere that `yarn` can be used as well?

> Setup: In the editors section, I'd remove “free” (some have paid options), add Visual Studio (and VS for Mac although I haven’t used it for a while), and move Rider up in the list.

ok

> Start a new project: I'd say "samples" instead of "templates" (which can be confused with dotnet templates or another templating system)

Yes you're right.

> Add a new file: mention that some editors do this for you (VS, Rider) and that file order in F# is important.

ok

> Use a Fable library: Maybe we can remove the explanation about .dll for general users (actually the .dll is used by editors, but Fable needs the source files in most cases so the compilation times is not faster). 

Ok. I think it would be really great if you could write a better `expert` stuff in some section anyway. Especially regarding the compiling process. 

> Also mention you can use the dotnet SDK command: dotnet add package Fable.Elmish.React [-v 3.0.1] and that some editors (VS, Rider) manage packages for you.

ok

> Use a Fable library: Important considerations: Maybe just reduce this to a note saying: “Please note the library must be specifically Fable-compatible in order to work.” Then we can add a link to another section for library authors to list the things necessary to write a library compatible with Fable, as in here: https://fable.io/faq/#library-authors

ok

> Build & Run: I would focus on Webpack for web projects instead of talking about npm start

ok so webpack first and let users discover about other tools in proper samples (rollup, splitter, etc...) in the `fable-samples` repo with documented `README` files?

> Call JS from Fable: I need to go through this document more throughly to make sure everything is up-to-date :)

Yes please ;) What is missing today is a better description and partical samples for js objects and maybe the use of Anonymous records?

> Call Fable from JS: We should add a note about name mangling in Fable, I’ll do that.

Thanks! 

> Numbers: decimal is currently not compiled to JS number, this is outdated in the docs, sorry! Add also a link to next document for number caveats when coming from .NET 

ok ;)

**Comment by whitetigle** [comment]
> Also, I do think we could benefit from a dedicated page called "Creating a Fable library" and we could walk step by step on how it can be done.

Yes let's do that!

**Comment by whitetigle** [comment]
> Build & Run: I would focus on Webpack for web projects instead of talking about npm start
> > It should indeed be more generalist. I guess some people could come to this section without having to start with a sample.

Would we a sample somewhere that would describe a manual process?
