### ISSUE TITLE
Rename repo to "docs"

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fable-doc#7]
This way we can publish the docs directly from here and automatically make them a section of fable.io as with the "repl" or "fableconf" repos.

**Comment by MangelMaxime** [comment]
Well, the documentation isn't ready so I prefer to not have a link from`fable.io` to this repo.

Also, I see this repo more like a replacement of the current `fable.io` website. Because `fable.io` is just a sort of custom `index.html` page that we can include in this repo.

**Comment by whitetigle** [comment]
So what you propose is to add a subproject here hosting the index and then cleanup the fable repo?

**Comment by whitetigle** [comment]
Ok so maybe we should put fableconf as well here to share the css and other assets?

**Comment by MangelMaxime** [comment]
My proposition is that when `fable-doc` is ready then we will be able to move the content of `fable-doc` repo into `fable-compiler.github.io`. So it will be the "main" website.

About hosting `fableconf` in the same repo, I am not sure if this a good or bad idea. I mean at the moment I copied the orange color from fableconf website indeed but just because I was lazy. At some point, we need to agree on a color theme for fable.io

Originally, it was blue just like with the logo but is it still the "fable" color or no. I don't know ^^

**Comment by whitetigle** [comment]
> At some point, we need to agree on a color theme for fable.io

Ok. Just so you know, basically we've planned to make a design sheet for all Fable related contents (web, doc, conf). It's a work in progress with my designer friend (Biensür Graphisme). We'll have fonts, colors, etc... We'll then propose something and we'll decide if that's ok.

Now the question is: in order to have people contribute to the doc, wouldn't it be better to keep a separate repo? The same question of course would apply to the blog. 
I'm not stuck with a specific scheme but I'd like to make the doc a real `live` folder, have more people interact. What do you think? Could a seperate folder make the path easier to more contributions? (I'm thinking about gathering some Fable/js and Fable/.NET people to help me)

**Comment by MangelMaxime** [comment]
>  Ok. Just so you know, basically we've planned to make a design sheet for all Fable related contents (web, doc, conf). It's a work in progress with my designer friend (Biensür Graphisme). We'll have fonts, colors, etc... We'll then propose something and we'll decide if that's ok.

That's really good news :)

> in order to have people contribute to the doc, wouldn't it be better to keep a separate repo?

Well so we would have a repo with a single `index.html` in it where no one would contribute. And then the "fable-doc" repo where contribution goes. Not sure of the benefit of the first repo :).

> The same question, of course, would apply to the blog

Nacara will be able to have a different type of pages and a plugin system. So you could have a "doc" page template, "blog" page template, etc. But every page will just be a simple `.md` file and Nacara will take care to understand what to do with it.

The idea, is that by default Nacara should be complete enough for writting easy to use documentation. And if you have a special needs then you can use the plugin system. I already have a few plugins that are hard coded in the code of Nacara and that I need to move as plugins. I hope to do it shortly so you can have an idea of what can be done.

>  I'd like to make the doc a real live folder, have more people interact. What do you think?

What do you mean by `live`?

In the past contribution to Fable documentation was hard because it was kind of complex to understand how to contribute to it. Sometimes, you had to write a `*.md` file, other times it was a list in an "Elmish application" etc. , they had to build a project using Fable itself which is not really a beginner friendly (takes times, it's hard to debug, you need to have an F# editor ready, etc.)

If from now, it is just about writing a markdown file and calling Nacara I think the process is much better. Or am I missing something?

My idea for the documentation is to make it as simple as possible for the user to contribute to it. And for that I think, I will make a PR to remove the `docs` folder from the tracked files to make this repo as slim as possible.

------------

*Everything I speak here will be do-able either by default thanks to Nacara or by a plugin that is a WIP at the moment :)*

In order to see what should be doable with Nacara and the proposed process here are some common scenarios:

**The user wants to fix typos or contribute to an existing page.**

1. He can edit the markdown file.
2. Optionally, he can start Nacara in order to see the changes in the browser.
3. Submit a PR.

It's worth noting that starting Nacara, is optional and so he can just edit the files from Github interface.

**The user wants to add a new page to  the documentation**

1. He needs to add the new entry to the `menu` node of `nacara.json`
2. He write the `newPage.md`
3. He can start Nacara in order to see the changes in the browser. (Still optional but it's better to do, in order to be sure everything is set up correctly)
4. Submi a PR.

**The user wants to add a new blog entry**

1. He just needs to add a new markdown files under a specifc folder like `blog` for example.
2. Submit a PR

**Comment by whitetigle** [comment]
Ok I'm convinced! 😄 
You're right, now all things will be straightforward with this new system 👍 
Great move ⚡️

**Comment by whitetigle** [comment]
I think we should link to the doc from the current fable.io web site since it will dramatically reduce friction for newcomers. Even if it's not yet complete it adresses many hot topics that will definitely help newcomers to come on board.

We'll see how to reorganize to one repo when I come with the new web design. 
Is that ok for you? If so I'll prepare a PR.

**Comment by MangelMaxime** [comment]
I would make the "Docs" navbar link from https://fable.io/ redirect directly to http://fable.io/fable-doc/

Personally, I prefer adding a message at the top of https://fable.io/docs/ saying that a WIP documentation is available at XXX. Explaining the design/content is not final but can be useful to them perhaps, blablabla

**Comment by whitetigle** [comment]
> I would make the "Docs" navbar link from https://fable.io/ redirect directly to http://fable.io/fable-doc/

👍

> Personally, I prefer adding a message at the top of https://fable.io/docs/ saying that a WIP documentation is available at XXX. Explaining the design/content is not final but can be useful to them perhaps, blablabla

👍
